name: deploy-lesspass-render-password-package

on:
  push:
    paths:
      - "packages/lesspass-render-password/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test lesspass-render-password package
        run: |
          yarn install
          yarn workspace lesspass-render-password run test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: deploy lesspass-render-password package
        run: |
          cd packages
          ./deploy lesspass-render-password
        continue-on-error: true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
